name: Flutter Web CI

on:
  push:
    branches:
      - main # メインブランチへのプッシュ時にトリガー

jobs:
  build:
    runs-on: ubuntu-20.04 # ビルド環境をubuntu-20.04に変更

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Flutterをセットアップ (バージョン3.27.2を指定)
      - name: Set up Flutter 3.27.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.2" # 明確にバージョン3.27.2を指定

      # 3. Flutterのキャッシュを修復
      - name: Clean Flutter cache
        run: flutter pub cache repair

      # 4. 依存関係をインストール
      - name: Install dependencies
        run: flutter pub get

      # 5. Flutter Webアプリをリリースモードでビルド
      - name: Build the web app
        run: flutter build web --release --verbose # 詳細なログを表示

      # 6. ビルドディレクトリの内容をリストアップ（デバッグ用）
      - name: List build directory
        run: ls -la ./build/web

      # 7. GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PWAGITHUBACTION }}
          publish_dir: ./build/web
