name: Flutter Web CI

on:
  push:
    branches:
      - main # メインブランチへのプッシュ時にトリガー

jobs:
  build:
    runs-on: ubuntu-20.04 # ビルド環境をubuntu-20.04に変更

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable" # 最新の安定版を使用

      - name: Install dependencies
        run: flutter pub get

      - name: Build the web app
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
